services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mediaarmy-app
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/html/src
      - ./index.php/:/var/www/html/index.php
    working_dir: /var/www/html
